import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";
import Navbar from "../components/ui/Navbar/Navbar";
import Herosection from "../components/sections/Herosection/Herosection";
import MobileMenu from "@/components/ui/MobileMenu/MobileMenu";
import Emailelement from "../components/ui/Sideelements/Emailelement/Emailelement";
import SocialLinks from "../components/ui/Sideelements/SocialLinks/SocialLinks";
import About from "../components/sections/About/About";
import Work from "../components/sections/Work/Work";
import ThingsIBuilt from "../components/sections/ThingsIBuilt/ThingsIBuilt";
import OtherProjects from "../components/sections/OtherProjects/OtherProjects";
import Footer from "../components/sections/Footer/Footer";
import sanityClient from "../utils/sanityClient";

const inter = Inter({ subsets: ["latin"] });
export default function Home(props: any) {
  console.log(props, "props");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Jubayer Juhan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ position: "relative" }}>
        <Navbar
          setMobileMenuOpen={setMobileMenuOpen}
          mobileMenuOpen={mobileMenuOpen}
        />

        <MobileMenu open={mobileMenuOpen} />
        {/* side elements*/}
        <Emailelement />
        <SocialLinks />
        <Herosection />
        <About />
        <Work />
        <ThingsIBuilt />
        <OtherProjects />
        <Footer />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  console.log("Hello World...");
  const data = await sanityClient.fetch(`*[_type == "siteSettings"][0]`);
  console.log(data, "dataaa....");

  return {
    props: data,
  };
};
