import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";
import Navbar from "../components/ui/Navbar/Navbar";
import Herosection from "../components/ui/Herosection/Herosection";
import MobileMenu from "@/components/ui/MobileMenu/MobileMenu";
import Emailelement from "../components/ui/Emailelement/Emailelement";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Jubayer Juhan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ position: "relative" }}>
        <Navbar
          setMobileMenuOpen={setMobileMenuOpen}
          mobileMenuOpen={mobileMenuOpen}
        />
        <MobileMenu open={mobileMenuOpen} />
        <Herosection />
        {/* side elements*/}
        <Emailelement />
      </main>
    </>
  );
}
